### ISSUE TITLE
Deployment is broken

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/jlink.online#27]
```
panic: html/template: pattern matches no files: `./templates/*.tmpl.html`

goroutine 1 [running]:
html/template.Must(...)
	/usr/lib/golang/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0000b6c80, 0xbda0ff, 0x17)
	/opt/app-root/src/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x362
main.main()
	/tmp/src/jlink.go:93 +0x57
```

We need to enable monitoring.

Is there an easy way to provide an endpoint for a health check?

**Comment by gdams** [comment]
I've switched to using the dockerfile in the repo which seems to be more stable

**Comment by aahlenst** [comment]
:+1: 

Working fine.
